### ISSUE TITLE
Feature request: Allow to open multiple files

### ISSUE THREAD

**Issue by azhinu** [spamwax/rmate-rs#3]
Hi. Can you add abillity to open multiple files at once? I mean `rmate file1 file2 etc`

**Comment by spamwax** [comment]
It already has that feature. Which editor you are using on the macOS side?
I know VSCode's extension for `rmate` does not open multiple files.

**Comment by spamwax** [comment]
I think I found the bug, I will work on a fix

**Comment by azhinu** [comment]
Thanks for your answer. I using VSCode, so seems the problem is here.

**Comment by spamwax** [comment]
Latest release should fix opening multiple files on TextMate client.
VSCode still doesn't support it even with official Ruby client.
